### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by klobuczek** [michael-simons/homebrew-seabolt#2]
I'm the author of https://github.com/neo4jrb/neo4j-ruby-driver. So far I've been downloading the pre-build seabolt library and referencing the download location from ffi like this:
```
ffi_lib ENV['SEABOLT_LIB']
```
If installed via brew do you know if there is a way without having to specify the full path of the library? Like loading from the standard library path?

**Comment by klobuczek** [comment]
Answering my own question. After brew installation, I can simply do:
```
ffi_lib 'libseabolt17'
```

**Comment by michael-simons** [comment]
Thanks Heinrich for your feedback! I wasn't fast enough (Diner time). I'm gonna share this however at the company. If this formula is helpful, we should move it to our contrib or driver org.
