### ISSUE TITLE
Installation fails on macOS 11.2.3 (with M1)

### ISSUE THREAD

**Issue by teomores** [michael-simons/homebrew-seabolt#5]
```⋊> ~/Downloads brew install michael-simons/homebrew-seabolt/seabolt
==> Installing seabolt from michael-simons/seabolt
==> Downloading https://github.com/neo4j-drivers/seabolt/archive/v1.7.4.tar.gz
Already downloaded: /Users/teomore/Library/Caches/Homebrew/downloads/54f73c543497043c3c1d9c1f5d447ed7c25361ed64473eb6ee4a2c8b13de0b96--seabolt-1.7.4.tar.gz
==> Patching
==> mkdir build
/opt/homebrew/Library/Taps/michael-simons/homebrew-seabolt/Formula/seabolt.rb:15: warning: conflicting chdir during another chdir block
==> cmake ..
==> cmake --build . --target install
Last 15 lines from /Users/teomore/Library/Logs/Homebrew/seabolt/03.cmake:
            CATCH_BREAK_INTO_DEBUGGER();
            ^
/tmp/seabolt-20210408-63066-1vzuqu5/seabolt-1.7.4/src/common/tests/catch.hpp:1392:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
                                                                          ^
/tmp/seabolt-20210408-63066-1vzuqu5/seabolt-1.7.4/src/common/tests/catch.hpp:1371:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
2 errors generated.
make[2]: *** [CMakeFiles/seabolt-test.dir/src/seabolt/tests/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/seabolt-test.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
```
I ran `brew install michael-simons/homebrew-seabolt/seabolt` and I also tried to build it from source (as described here -> https://github.com/neo4j-drivers/seabolt#macos-x), but in both cases I got the same issue. Is this something related to the M1? How can I solve it?

Thanks in advance.

**Comment by teomores** [comment]
Replacing the `catch.hpp` with the updated one as described [here](https://github.com/mlpack/ensmallen/issues/266) and build from source actually solves this specific issue.

**Comment by michael-simons** [comment]
Thanks for your feedback, Matteo!

**Comment by teomores** [comment]
Unfortunately I'm getting a new problem:
```
In file included from /Users/teomore/Documents/seabolt-1.7.4/src/seabolt/tests/test-communication.cpp:26:
/Users/teomore/Documents/seabolt-1.7.4/src/seabolt/tests/utils/test-context.h:85:28: error: 
      implicit instantiation of undefined template
      'std::__1::basic_ostringstream<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
        std::ostringstream ss;
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:136:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_ostringstream;
                               ^
1 error generated.
make[2]: *** [CMakeFiles/seabolt-test.dir/src/seabolt/tests/test-communication.cpp.o] Error 1
make[1]: *** [CMakeFiles/seabolt-test.dir/all] Error 2
make: *** [all] Error 2
```
I assume this is still related to the M1. Do you happen to know how to solve this? Or do you know if someone has successfully installed the package with the M1? 
Thanks in advance.

**Comment by michael-simons** [comment]
Tbh, I don't think there will be any further development on the Seabolt library. I asked around internally, but afaik there's no colleague with an M1 so far.

**Comment by teomores** [comment]
Okay, no worries, I'm having some new issue but I'll try to figure it out myself. Thanks anyways!

**Comment by hraynaud** [comment]
@teomores thanks for you post. I could use your help since it appears you were able to work this problem out. 
I'm need seabolet installed as part of dependency for neo4j.rb ruby gem and neo4j _ruby_driver. 
I followed the steps in the [workaround](https://github.com/mlpack/ensmallen/issues/266) you referenced. Other than the fact that there was not catch2.hpp everything seemed to work fine.
However I still get the same error. Is there another step involved in pointing my application to the right version of ensmallen? 
Thanks.

**Comment by teomores** [comment]
Hi @hraynaud!
Me and my team are also using seabolt as a dependency for neo4j.rb and the ruby driver, and everything seems to work fine. I solved my issues changing a couple of things with respect to the original [seabolt driver](https://github.com/neo4j-drivers/seabolt), this is [my forked repo](https://github.com/teomores/seabolt-M1), you can try to reproduce the steps in the README. Let me know if you come by an issue!

**Comment by hraynaud** [comment]
@teomores 

Thanks for the response.  I followed the  instructions in your repo but the build is still failing for me. I've set the OPENSSL_ROOT_DIR envirorment variable but somehow openssl is still not found:

```
➜  seabolt-M1 git:(M1_support) ENV | grep OPEN
OPENSSL_ROOT_DIR=/usr/local/opt/openssl
```


```
➜  seabolt-M1 git:(M1_support) ✗ ./make_release.sh

-- Building seabolt: 1.7.4-dev
-- Building seabolt with TLS support
-- Using OPENSSL for TLS
CMake Error at /opt/homebrew/Cellar/cmake/3.20.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.20.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.20.5/share/cmake/Modules/FindOpenSSL.cmake:570 (find_package_handle_standard_args)
  cmake/Internals.cmake:41 (find_package)
  src/seabolt/src/CMakeLists.txt:109 (find_openssl_both)
  src/seabolt/CMakeLists.txt:5 (include)
  src/CMakeLists.txt:14 (include)
  CMakeLists.txt:112 (include)
```
Not sure what to do next since I'm very unfamiliar with the cmake command.

**Comment by hraynaud** [comment]
@teomores what version of openssl are you using? Do I need to install 1.0 in order for your fork to work?

**Comment by teomores** [comment]
Hey @hraynaud !

Have you checked that the path to openssl is correct for you? `/usr/local/opt/openssl` was the default one for brew, but with the apple chip I think that brew packages are located somewhere different, something that looks like `/opt/homebrew/opt/openssl`. You can simply check it by doing `brew --prefix openssl`.

Let me know if this was the problem!

**Comment by hraynaud** [comment]
thanks for getting back to me. yep that was the trick! really appreciate your help.
